@api = http://localhost:3000

GET {{api}}/sensor/temperature

###
GET {{api}}/sensor/humidity

###
GET {{api}}/sensor/pressure

###
GET {{api}}/sensor/latest

###
GET {{api}}/sensor/last-week

###
GET {{api}}/sensor/yesterday