@api = http://smartreflectbe-env.eba-6h3empqx.eu-west-1.elasticbeanstalk.com

GET {{api}}/sensor/temperature

###
GET {{api}}/sensor/humidity

###
GET {{api}}/sensor/pressure

###
GET {{api}}/sensor/latest

###
GET {{api}}/sensor/last-week

###
GET {{api}}/sensor/yesterday